name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest chispa pyspark==3.5.0 delta-spark

      - name: Run all tests (Bronze + Silver + Gold)
        run: PYTHONPATH=src pytest -v tests/ --disable-warnings
